package main

import (
	"log"
	"os"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/elberthcabrales/movies-api/docs" // generated by swag
	"github.com/elberthcabrales/movies-api/pkg/cache"
	"github.com/elberthcabrales/movies-api/pkg/config"
	"github.com/elberthcabrales/movies-api/pkg/repositories"
	"github.com/elberthcabrales/movies-api/pkg/router"
	"github.com/elberthcabrales/movies-api/pkg/services"
)

func initializeServer() *gin.Engine {
	// Load Redis configuration
	log.Println("Loading Redis configuration...")
	redisConfig := config.LoadConfig()
	redisCache := cache.NewRedisCache(nil, redisConfig)
	token := os.Getenv("TOKEN")

	// Initialize MovieRepository
	log.Println("Initializing MovieRepository...")
	movieRepo := repositories.NewMovieRepository(token, redisCache)

	// Initialize MovieService
	log.Println("Initializing MovieService...")
	movieService := services.NewMovieService(movieRepo)

	// Initialize Router
	log.Println("Setting up routes...")
	movieRouter := router.NewMovieRouter(movieService)
	r := movieRouter.SetupRouter()

	// Swagger endpoint
	log.Println("Setting up Swagger documentation...")
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}

func main() {
	log.Println("Starting server...")
	r := initializeServer()
	if err := r.Run(":8080"); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
	log.Println("Server is running on port 8080")
}
